# Model Building

1. Import Libraries

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder,
    LabelEncoder
)

from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline

# All Models

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

2. Load Dataset

In [4]:
df = pd.read_csv("../data/WA_Fn-UseC_-HR-Employee-Attrition.csv")

3. Remove Unnecessary Columns

In [5]:
df.drop(
    columns=[
        "EmployeeNumber",
        "EmployeeCount",
        "Over18",
        "StandardHours"
    ],
    inplace =True
)

4. Encode Target

In [6]:
le = LabelEncoder()

df["Attrition"] = le.fit_transform(df["Attrition"])

5. Split Features and Target

In [7]:
x = df.drop("Attrition", axis = 1)
y = df["Attrition"]

6. Identify Numerical and Categorical Columns

In [17]:
numerical_columns = x.select_dtypes(include=["int64"]).columns
categorical_columns = x.select_dtypes(include=["object"]).columns

/var/folders/83/lyk88fr96bq5vfw5v_m3j0n40000gn/T/ipykernel_7779/2031502495.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = x.select_dtypes(include=["object"]).columns


7. Create Preprocessor

In [9]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_columns
        ),
        (
            "cat",
            OneHotEncoder(drop="first"),
            categorical_columns
        )
    ]
)

8. Train-Test Split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42,
    stratify = y
)

9. Create Model Dictionary

In [13]:
models = {
    "LogisticRegression": LogisticRegression(random_state=42),
    "KNN": KNeighborsClassifier(),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "SVM": SVC(random_state=42),
}

10. Train Models

In [15]:
trained_models = {}

for name, model in models.items():
    pipeline = Pipeline([
        ("Preprocessor", preprocessor),
        ("classifier", model)
    ])

    pipeline.fit(x_train, y_train)
    trained_models[name] = pipeline 

    print(f"{name} trained successfully.")

LogisticRegression trained successfully.
KNN trained successfully.
DecisionTree trained successfully.
Random Forest trained successfully.
SVM trained successfully.


11. Make Predictions

In [18]:
predictions = {}

for name, model in trained_models.items():
    predictions[name] = model.predict(x_test)

12. Check Predictions

In [20]:
for name in predictions:
    print("="*50)
    print(name)
    print(predictions[name][:10])

LogisticRegression
[0 0 0 0 0 0 0 0 0 0]
KNN
[0 0 0 0 0 0 0 0 0 0]
DecisionTree
[1 0 0 0 1 0 0 0 0 1]
Random Forest
[1 0 0 0 0 0 0 0 0 1]
SVM
[0 0 0 0 0 0 0 0 0 0]


## Summary

### Objective
Built multiple machine learning classification models using a reusable Scikit-Learn pipeline.

### Models Trained
- Logistic Regression
- K-Nearest Neighbors (KNN)
- Decision Tree
- Random Forest
- Support Vector Machine (SVM)

### Tasks Performed
- Loaded and prepared the dataset.
- Removed unnecessary columns.
- Encoded the target variable.
- Identified numerical and categorical features.
- Created a preprocessing pipeline using `ColumnTransformer`.
- Built reusable model pipelines with `Pipeline`.
- Trained 5 classification models.
- Generated predictions on the test dataset.

### Key Learnings
- Pipelines simplify preprocessing and model training.
- Using a common preprocessing pipeline ensures fair model comparison.
- Training multiple models helps identify the most suitable algorithm for the problem.

### Outcome
5 machine learning models have been successfully trained and are ready for evaluation in the next phase.